export DATABASE_URI="$DATABASE_URL"?sslmode=require
export PAYLOAD_SECRET="$(echo "$VCAP_SERVICES" | jq --raw-output --arg service_name "pages-editor-$APP_ENV-creds" ".[][] | select(.name == \$service_name) | .credentials.PAYLOAD_SECRET")"
export OAUTH_CLIENT_ID="$(echo "$VCAP_SERVICES" | jq --raw-output --arg service_name "pages-editor-$APP_ENV-creds" ".[][] | select(.name == \$service_name) | .credentials.OAUTH_CLIENT_ID")"
export OAUTH_CLIENT_SECRET="$(echo "$VCAP_SERVICES" | jq --raw-output --arg service_name "pages-editor-$APP_ENV-creds" ".[][] | select(.name == \$service_name) | .credentials.OAUTH_CLIENT_SECRET")"
export EMAIL_HOST="$(echo "$VCAP_SERVICES" | jq --raw-output --arg service_name "pages-editor-$APP_ENV-creds" ".[][] | select(.name == \$service_name) | .credentials.EMAIL_HOST")"
export EMAIL_USERNAME="$(echo "$VCAP_SERVICES" | jq --raw-output --arg service_name "pages-editor-$APP_ENV-creds" ".[][] | select(.name == \$service_name) | .credentials.EMAIL_USERNAME")"
export EMAIL_PASSWORD="$(echo "$VCAP_SERVICES" | jq --raw-output --arg service_name "pages-editor-$APP_ENV-creds" ".[][] | select(.name == \$service_name) | .credentials.EMAIL_PASSWORD")"
export PAGES_ENCRYPTION_KEY="$(echo "$VCAP_SERVICES" | jq --raw-output --arg service_name "pages-editor-$APP_ENV-creds" ".[][] | select(.name == \$service_name) | .credentials.PAGES_ENCRYPTION_KEY")"
export SITE_METADATA_BUCKET="$(echo "$VCAP_SERVICES" | jq --raw-output --arg service_name "pages-editor-$APP_ENV-s3" ".[][] | select(.name == \$service_name) | .credentials.bucket")"
export AWS_ACCESS_KEY_ID="$(echo "$VCAP_SERVICES" | jq --raw-output --arg service_name "pages-editor-$APP_ENV-s3" ".[][] | select(.name == \$service_name) | .credentials.access_key_id")"
export AWS_SECRET_ACCESS_KEY="$(echo "$VCAP_SERVICES" | jq --raw-output --arg service_name "pages-editor-$APP_ENV-s3" ".[][] | select(.name == \$service_name) | .credentials.secret_access_key")"
export AWS_REGION="$(echo "$VCAP_SERVICES" | jq --raw-output --arg service_name "pages-editor-$APP_ENV-s3" ".[][] | select(.name == \$service_name) | .credentials.region")"
export STORAGE_ENDPOINT_URL="https://$(echo "$VCAP_SERVICES" | jq --raw-output --arg service_name "pages-editor-$APP_ENV-s3" ".[][] | select(.name == \$service_name) | .credentials.endpoint")"
