# Use a base Node.js image
FROM node:22.12.0-bullseye

COPY ./Zscaler_Root_CA.pem /usr/local/share/ca-certificates/zscaler.crt
RUN update-ca-certificates

WORKDIR /app

ARG SITE_GANTRY_TAG

RUN wget -O main.zip https://github.com/cloud-gov/pages-site-gantry/archive/refs/tags/${SITE_GANTRY_TAG}.zip && \
    unzip main.zip && mv pages-site-gantry-${SITE_GANTRY_TAG}/* . && \
    rm -rf pages-site-gantry-${SITE_GANTRY_TAG} main.zip

RUN npm ci

EXPOSE 4321
