export type UswdsColorToken = {
  token: string
  hex: string
  family: string
}

export const uswdsColorTokens: UswdsColorToken[] = [
  { token: 'white', hex: '#ffffff', family: 'Base' },
  { token: 'black', hex: '#000000', family: 'Base' },

  { token: 'red-cool-5', hex: '#f8eff1', family: 'Red Cool' },
  { token: 'red-cool-10', hex: '#f3e1e4', family: 'Red Cool' },
  { token: 'red-cool-20', hex: '#ecbec6', family: 'Red Cool' },
  { token: 'red-cool-30', hex: '#e09aa6', family: 'Red Cool' },
  { token: 'red-cool-40', hex: '#e16b80', family: 'Red Cool' },
  { token: 'red-cool-50', hex: '#cd425b', family: 'Red Cool' },
  { token: 'red-cool-60', hex: '#9e394b', family: 'Red Cool' },
  { token: 'red-cool-70', hex: '#68363f', family: 'Red Cool' },
  { token: 'red-cool-80', hex: '#40282c', family: 'Red Cool' },
  { token: 'red-cool-90', hex: '#1e1517', family: 'Red Cool' },
  { token: 'red-cool-5v', hex: '#fff2f5', family: 'Red Cool' },
  { token: 'red-cool-10v', hex: '#f8dfe2', family: 'Red Cool' },
  { token: 'red-cool-20v', hex: '#f8b9c5', family: 'Red Cool' },
  { token: 'red-cool-30v', hex: '#fd8ba0', family: 'Red Cool' },
  { token: 'red-cool-40v', hex: '#f45d79', family: 'Red Cool' },
  { token: 'red-cool-50v', hex: '#e41d3d', family: 'Red Cool' },
  { token: 'red-cool-60v', hex: '#b21d38', family: 'Red Cool' },
  { token: 'red-cool-70v', hex: '#822133', family: 'Red Cool' },
  { token: 'red-cool-80v', hex: '#4f1c24', family: 'Red Cool' },

  { token: 'red-5', hex: '#f9eeee', family: 'Red' },
  { token: 'red-10', hex: '#f8e1de', family: 'Red' },
  { token: 'red-20', hex: '#f7bbb1', family: 'Red' },
  { token: 'red-30', hex: '#f2938c', family: 'Red' },
  { token: 'red-40', hex: '#e9695f', family: 'Red' },
  { token: 'red-50', hex: '#d83933', family: 'Red' },
  { token: 'red-60', hex: '#a23737', family: 'Red' },
  { token: 'red-70', hex: '#6f3331', family: 'Red' },
  { token: 'red-80', hex: '#3e2927', family: 'Red' },
  { token: 'red-90', hex: '#1b1616', family: 'Red' },
  { token: 'red-5v', hex: '#fff3f2', family: 'Red' },
  { token: 'red-10v', hex: '#fde0db', family: 'Red' },
  { token: 'red-20v', hex: '#fdb8ae', family: 'Red' },
  { token: 'red-30v', hex: '#ff8d7b', family: 'Red' },
  { token: 'red-40v', hex: '#fb5a47', family: 'Red' },
  { token: 'red-50v', hex: '#e52207', family: 'Red' },
  { token: 'red-60v', hex: '#b50909', family: 'Red' },
  { token: 'red-70v', hex: '#8b0a03', family: 'Red' },
  { token: 'red-80v', hex: '#5c1111', family: 'Red' },

  { token: 'red-warm-5', hex: '#f6efea', family: 'Red Warm' },
  { token: 'red-warm-10', hex: '#f4e3db', family: 'Red Warm' },
  { token: 'red-warm-20', hex: '#ecc0a7', family: 'Red Warm' },
  { token: 'red-warm-30', hex: '#dca081', family: 'Red Warm' },
  { token: 'red-warm-40', hex: '#d27a56', family: 'Red Warm' },
  { token: 'red-warm-50', hex: '#c3512c', family: 'Red Warm' },
  { token: 'red-warm-60', hex: '#805039', family: 'Red Warm' },
  { token: 'red-warm-70', hex: '#524236', family: 'Red Warm' },
  { token: 'red-warm-80', hex: '#332d29', family: 'Red Warm' },
  { token: 'red-warm-90', hex: '#1f1c18', family: 'Red Warm' },
  { token: 'red-warm-5v', hex: '#fff5ee', family: 'Red Warm' },
  { token: 'red-warm-10v', hex: '#fce1d4', family: 'Red Warm' },
  { token: 'red-warm-20v', hex: '#f6bd9c', family: 'Red Warm' },
  { token: 'red-warm-30v', hex: '#f39268', family: 'Red Warm' },
  { token: 'red-warm-40v', hex: '#ef5e25', family: 'Red Warm' },
  { token: 'red-warm-50v', hex: '#d54309', family: 'Red Warm' },
  { token: 'red-warm-60v', hex: '#9c3d10', family: 'Red Warm' },
  { token: 'red-warm-70v', hex: '#63340f', family: 'Red Warm' },
  { token: 'red-warm-80v', hex: '#3e2a1e', family: 'Red Warm' },

  { token: 'orange-warm-5', hex: '#faeee5', family: 'Orange Warm' },
  { token: 'orange-warm-10', hex: '#fbe0d0', family: 'Orange Warm' },
  { token: 'orange-warm-20', hex: '#f7bca2', family: 'Orange Warm' },
  { token: 'orange-warm-30', hex: '#f3966d', family: 'Orange Warm' },
  { token: 'orange-warm-40', hex: '#e17141', family: 'Orange Warm' },
  { token: 'orange-warm-50', hex: '#bd5727', family: 'Orange Warm' },
  { token: 'orange-warm-60', hex: '#914734', family: 'Orange Warm' },
  { token: 'orange-warm-70', hex: '#633a32', family: 'Orange Warm' },
  { token: 'orange-warm-80', hex: '#3d2925', family: 'Orange Warm' },
  { token: 'orange-warm-90', hex: '#1c1615', family: 'Orange Warm' },
  { token: 'orange-warm-5v', hex: '#fff3ea', family: 'Orange Warm' },
  { token: 'orange-warm-10v', hex: '#ffe2d1', family: 'Orange Warm' },
  { token: 'orange-warm-20v', hex: '#fbbaa7', family: 'Orange Warm' },
  { token: 'orange-warm-30v', hex: '#fc906d', family: 'Orange Warm' },
  { token: 'orange-warm-40v', hex: '#ff580a', family: 'Orange Warm' },
  { token: 'orange-warm-50v', hex: '#cf4900', family: 'Orange Warm' },
  { token: 'orange-warm-60v', hex: '#a72f10', family: 'Orange Warm' },
  { token: 'orange-warm-70v', hex: '#782312', family: 'Orange Warm' },
  { token: 'orange-warm-80v', hex: '#3d231d', family: 'Orange Warm' },

  { token: 'orange-5', hex: '#f6efe9', family: 'Orange' },
  { token: 'orange-10', hex: '#f2e4d4', family: 'Orange' },
  { token: 'orange-20', hex: '#f3bf90', family: 'Orange' },
  { token: 'orange-30', hex: '#f09860', family: 'Orange' },
  { token: 'orange-40', hex: '#dd7533', family: 'Orange' },
  { token: 'orange-50', hex: '#a86437', family: 'Orange' },
  { token: 'orange-60', hex: '#775540', family: 'Orange' },
  { token: 'orange-70', hex: '#524236', family: 'Orange' },
  { token: 'orange-80', hex: '#332d27', family: 'Orange' },
  { token: 'orange-90', hex: '#1b1614', family: 'Orange' },
  { token: 'orange-5v', hex: '#fef2e4', family: 'Orange' },
  { token: 'orange-10v', hex: '#fce2c5', family: 'Orange' },
  { token: 'orange-20v', hex: '#ffbc78', family: 'Orange' },
  { token: 'orange-30v', hex: '#fa9441', family: 'Orange' },
  { token: 'orange-40v', hex: '#e66f0e', family: 'Orange' },
  { token: 'orange-50v', hex: '#c05600', family: 'Orange' },
  { token: 'orange-60v', hex: '#8c471c', family: 'Orange' },
  { token: 'orange-70v', hex: '#5f3617', family: 'Orange' },
  { token: 'orange-80v', hex: '#352313', family: 'Orange' },

  { token: 'gold-5', hex: '#f5f0e6', family: 'Gold' },
  { token: 'gold-10', hex: '#f1e5cd', family: 'Gold' },
  { token: 'gold-20', hex: '#dec69a', family: 'Gold' },
  { token: 'gold-30', hex: '#c7a97b', family: 'Gold' },
  { token: 'gold-40', hex: '#ad8b65', family: 'Gold' },
  { token: 'gold-50', hex: '#8e704f', family: 'Gold' },
  { token: 'gold-60', hex: '#6b5947', family: 'Gold' },
  { token: 'gold-70', hex: '#4d4438', family: 'Gold' },
  { token: 'gold-80', hex: '#322d26', family: 'Gold' },
  { token: 'gold-90', hex: '#191714', family: 'Gold' },
  { token: 'gold-5v', hex: '#fef0c8', family: 'Gold' },
  { token: 'gold-10v', hex: '#ffe396', family: 'Gold' },
  { token: 'gold-20v', hex: '#ffbe2e', family: 'Gold' },
  { token: 'gold-30v', hex: '#e5a000', family: 'Gold' },
  { token: 'gold-40v', hex: '#c2850c', family: 'Gold' },
  { token: 'gold-50v', hex: '#936f38', family: 'Gold' },
  { token: 'gold-60v', hex: '#7a591a', family: 'Gold' },
  { token: 'gold-70v', hex: '#5c410a', family: 'Gold' },
  { token: 'gold-80v', hex: '#3b2b15', family: 'Gold' },

  { token: 'yellow-5', hex: '#faf3d1', family: 'Yellow' },
  { token: 'yellow-10', hex: '#f5e6af', family: 'Yellow' },
  { token: 'yellow-20', hex: '#e6c74c', family: 'Yellow' },
  { token: 'yellow-30', hex: '#c9ab48', family: 'Yellow' },
  { token: 'yellow-40', hex: '#a88f48', family: 'Yellow' },
  { token: 'yellow-50', hex: '#8a7237', family: 'Yellow' },
  { token: 'yellow-60', hex: '#6b5a39', family: 'Yellow' },
  { token: 'yellow-70', hex: '#504332', family: 'Yellow' },
  { token: 'yellow-80', hex: '#332d27', family: 'Yellow' },
  { token: 'yellow-90', hex: '#1a1614', family: 'Yellow' },
  { token: 'yellow-5v', hex: '#fff5c2', family: 'Yellow' },
  { token: 'yellow-10v', hex: '#fee685', family: 'Yellow' },
  { token: 'yellow-20v', hex: '#face00', family: 'Yellow' },
  { token: 'yellow-30v', hex: '#ddaa01', family: 'Yellow' },
  { token: 'yellow-40v', hex: '#b38c00', family: 'Yellow' },
  { token: 'yellow-50v', hex: '#947100', family: 'Yellow' },
  { token: 'yellow-60v', hex: '#776017', family: 'Yellow' },
  { token: 'yellow-70v', hex: '#5c4809', family: 'Yellow' },
  { token: 'yellow-80v', hex: '#422d19', family: 'Yellow' },

  { token: 'green-warm-5', hex: '#f1f4d7', family: 'Green Warm' },
  { token: 'green-warm-10', hex: '#e7eab7', family: 'Green Warm' },
  { token: 'green-warm-20', hex: '#cbd17a', family: 'Green Warm' },
  { token: 'green-warm-30', hex: '#a6b557', family: 'Green Warm' },
  { token: 'green-warm-40', hex: '#8a984b', family: 'Green Warm' },
  { token: 'green-warm-50', hex: '#6f7a41', family: 'Green Warm' },
  { token: 'green-warm-60', hex: '#5a5f38', family: 'Green Warm' },
  { token: 'green-warm-70', hex: '#45472f', family: 'Green Warm' },
  { token: 'green-warm-80', hex: '#2d2f21', family: 'Green Warm' },
  { token: 'green-warm-90', hex: '#171712', family: 'Green Warm' },
  { token: 'green-warm-5v', hex: '#f5fbc1', family: 'Green Warm' },
  { token: 'green-warm-10v', hex: '#e7f434', family: 'Green Warm' },
  { token: 'green-warm-20v', hex: '#c5d30a', family: 'Green Warm' },
  { token: 'green-warm-30v', hex: '#a3b72c', family: 'Green Warm' },
  { token: 'green-warm-40v', hex: '#7e9c1d', family: 'Green Warm' },
  { token: 'green-warm-50v', hex: '#6a7d00', family: 'Green Warm' },
  { token: 'green-warm-60v', hex: '#5a6613', family: 'Green Warm' },
  { token: 'green-warm-70v', hex: '#4b4e10', family: 'Green Warm' },
  { token: 'green-warm-80v', hex: '#38380b', family: 'Green Warm' },

  { token: 'green-5', hex: '#eaf4dd', family: 'Green' },
  { token: 'green-10', hex: '#dfeacd', family: 'Green' },
  { token: 'green-20', hex: '#b8d293', family: 'Green' },
  { token: 'green-30', hex: '#9bb672', family: 'Green' },
  { token: 'green-40', hex: '#7d9b4e', family: 'Green' },
  { token: 'green-50', hex: '#607f35', family: 'Green' },
  { token: 'green-60', hex: '#4c6424', family: 'Green' },
  { token: 'green-70', hex: '#3c4a29', family: 'Green' },
  { token: 'green-80', hex: '#293021', family: 'Green' },
  { token: 'green-90', hex: '#161814', family: 'Green' },
  { token: 'green-5v', hex: '#ddf9c7', family: 'Green' },
  { token: 'green-10v', hex: '#c5ee93', family: 'Green' },
  { token: 'green-20v', hex: '#98d035', family: 'Green' },
  { token: 'green-30v', hex: '#7fb135', family: 'Green' },
  { token: 'green-40v', hex: '#719f2a', family: 'Green' },
  { token: 'green-50v', hex: '#538200', family: 'Green' },
  { token: 'green-60v', hex: '#466c04', family: 'Green' },
  { token: 'green-70v', hex: '#2f4a0b', family: 'Green' },
  { token: 'green-80v', hex: '#243413', family: 'Green' },

  { token: 'green-cool-5', hex: '#ecf3ec', family: 'Green Cool' },
  { token: 'green-cool-10', hex: '#dbebde', family: 'Green Cool' },
  { token: 'green-cool-20', hex: '#b4d0b9', family: 'Green Cool' },
  { token: 'green-cool-30', hex: '#86b98e', family: 'Green Cool' },
  { token: 'green-cool-40', hex: '#5e9f69', family: 'Green Cool' },
  { token: 'green-cool-50', hex: '#4d8055', family: 'Green Cool' },
  { token: 'green-cool-60', hex: '#446443', family: 'Green Cool' },
  { token: 'green-cool-70', hex: '#37493b', family: 'Green Cool' },
  { token: 'green-cool-80', hex: '#28312a', family: 'Green Cool' },
  { token: 'green-cool-90', hex: '#1a1f1a', family: 'Green Cool' },
  { token: 'green-cool-5v', hex: '#e3f5e1', family: 'Green Cool' },
  { token: 'green-cool-10v', hex: '#b7f5bd', family: 'Green Cool' },
  { token: 'green-cool-20v', hex: '#70e17b', family: 'Green Cool' },
  { token: 'green-cool-30v', hex: '#21c834', family: 'Green Cool' },
  { token: 'green-cool-40v', hex: '#00a91c', family: 'Green Cool' },
  { token: 'green-cool-50v', hex: '#008817', family: 'Green Cool' },
  { token: 'green-cool-60v', hex: '#216e1f', family: 'Green Cool' },
  { token: 'green-cool-70v', hex: '#154c21', family: 'Green Cool' },
  { token: 'green-cool-80v', hex: '#19311e', family: 'Green Cool' },

  { token: 'mint-5', hex: '#dbf6ed', family: 'Mint' },
  { token: 'mint-10', hex: '#c7efe2', family: 'Mint' },
  { token: 'mint-20', hex: '#92d9bb', family: 'Mint' },
  { token: 'mint-30', hex: '#5abf95', family: 'Mint' },
  { token: 'mint-40', hex: '#34a37e', family: 'Mint' },
  { token: 'mint-50', hex: '#2e8367', family: 'Mint' },
  { token: 'mint-60', hex: '#286846', family: 'Mint' },
  { token: 'mint-70', hex: '#204e34', family: 'Mint' },
  { token: 'mint-80', hex: '#193324', family: 'Mint' },
  { token: 'mint-90', hex: '#0d1a12', family: 'Mint' },
  { token: 'mint-5v', hex: '#c9fbeb', family: 'Mint' },
  { token: 'mint-10v', hex: '#83fcd4', family: 'Mint' },
  { token: 'mint-20v', hex: '#0ceda6', family: 'Mint' },
  { token: 'mint-30v', hex: '#04c585', family: 'Mint' },
  { token: 'mint-40v', hex: '#00a871', family: 'Mint' },
  { token: 'mint-50v', hex: '#008659', family: 'Mint' },
  { token: 'mint-60v', hex: '#146947', family: 'Mint' },
  { token: 'mint-70v', hex: '#0c4e29', family: 'Mint' },
  { token: 'mint-80v', hex: '#0d351e', family: 'Mint' },

  { token: 'mint-cool-5', hex: '#e0f7f6', family: 'Mint Cool' },
  { token: 'mint-cool-10', hex: '#c4eeeb', family: 'Mint Cool' },
  { token: 'mint-cool-20', hex: '#9bd4cf', family: 'Mint Cool' },
  { token: 'mint-cool-30', hex: '#6fbab3', family: 'Mint Cool' },
  { token: 'mint-cool-40', hex: '#4f9e99', family: 'Mint Cool' },
  { token: 'mint-cool-50', hex: '#40807e', family: 'Mint Cool' },
  { token: 'mint-cool-60', hex: '#376462', family: 'Mint Cool' },
  { token: 'mint-cool-70', hex: '#2a4b45', family: 'Mint Cool' },
  { token: 'mint-cool-80', hex: '#203131', family: 'Mint Cool' },
  { token: 'mint-cool-90', hex: '#111818', family: 'Mint Cool' },
  { token: 'mint-cool-5v', hex: '#d5fbf3', family: 'Mint Cool' },
  { token: 'mint-cool-10v', hex: '#7efbe1', family: 'Mint Cool' },
  { token: 'mint-cool-20v', hex: '#29e1cb', family: 'Mint Cool' },
  { token: 'mint-cool-30v', hex: '#1dc2ae', family: 'Mint Cool' },
  { token: 'mint-cool-40v', hex: '#00a398', family: 'Mint Cool' },
  { token: 'mint-cool-50v', hex: '#008480', family: 'Mint Cool' },
  { token: 'mint-cool-60v', hex: '#0f6460', family: 'Mint Cool' },
  { token: 'mint-cool-70v', hex: '#0b4b3f', family: 'Mint Cool' },
  { token: 'mint-cool-80v', hex: '#123131', family: 'Mint Cool' },

  { token: 'cyan-5', hex: '#e7f6f8', family: 'Cyan' },
  { token: 'cyan-10', hex: '#ccecf2', family: 'Cyan' },
  { token: 'cyan-20', hex: '#99deea', family: 'Cyan' },
  { token: 'cyan-30', hex: '#5dc0d1', family: 'Cyan' },
  { token: 'cyan-40', hex: '#449dac', family: 'Cyan' },
  { token: 'cyan-50', hex: '#168092', family: 'Cyan' },
  { token: 'cyan-60', hex: '#2a646d', family: 'Cyan' },
  { token: 'cyan-70', hex: '#2c4a4e', family: 'Cyan' },
  { token: 'cyan-80', hex: '#203133', family: 'Cyan' },
  { token: 'cyan-90', hex: '#111819', family: 'Cyan' },
  { token: 'cyan-5v', hex: '#e5faff', family: 'Cyan' },
  { token: 'cyan-10v', hex: '#a8f2ff', family: 'Cyan' },
  { token: 'cyan-20v', hex: '#52daf2', family: 'Cyan' },
  { token: 'cyan-30v', hex: '#00bde3', family: 'Cyan' },
  { token: 'cyan-40v', hex: '#009ec1', family: 'Cyan' },
  { token: 'cyan-50v', hex: '#0081a1', family: 'Cyan' },
  { token: 'cyan-60v', hex: '#00687d', family: 'Cyan' },
  { token: 'cyan-70v', hex: '#0e4f5c', family: 'Cyan' },
  { token: 'cyan-80v', hex: '#093b44', family: 'Cyan' },

  { token: 'blue-cool-5', hex: '#e7f2f5', family: 'Blue Cool' },
  { token: 'blue-cool-10', hex: '#dae9ee', family: 'Blue Cool' },
  { token: 'blue-cool-20', hex: '#adcfdc', family: 'Blue Cool' },
  { token: 'blue-cool-30', hex: '#82b4c9', family: 'Blue Cool' },
  { token: 'blue-cool-40', hex: '#6499af', family: 'Blue Cool' },
  { token: 'blue-cool-50', hex: '#3a7d95', family: 'Blue Cool' },
  { token: 'blue-cool-60', hex: '#2e6276', family: 'Blue Cool' },
  { token: 'blue-cool-70', hex: '#224a58', family: 'Blue Cool' },
  { token: 'blue-cool-80', hex: '#14333d', family: 'Blue Cool' },
  { token: 'blue-cool-90', hex: '#0f191c', family: 'Blue Cool' },
  { token: 'blue-cool-5v', hex: '#e1f3f8', family: 'Blue Cool' },
  { token: 'blue-cool-10v', hex: '#c3ebfa', family: 'Blue Cool' },
  { token: 'blue-cool-20v', hex: '#97d4ea', family: 'Blue Cool' },
  { token: 'blue-cool-30v', hex: '#59b9de', family: 'Blue Cool' },
  { token: 'blue-cool-40v', hex: '#28a0cb', family: 'Blue Cool' },
  { token: 'blue-cool-50v', hex: '#0d7ea2', family: 'Blue Cool' },
  { token: 'blue-cool-60v', hex: '#07648d', family: 'Blue Cool' },
  { token: 'blue-cool-70v', hex: '#074b69', family: 'Blue Cool' },
  { token: 'blue-cool-80v', hex: '#002d3f', family: 'Blue Cool' },

  { token: 'blue-5', hex: '#eff6fb', family: 'Blue' },
  { token: 'blue-10', hex: '#d9e8f6', family: 'Blue' },
  { token: 'blue-20', hex: '#aacdec', family: 'Blue' },
  { token: 'blue-30', hex: '#73b3e7', family: 'Blue' },
  { token: 'blue-40', hex: '#4f97d1', family: 'Blue' },
  { token: 'blue-50', hex: '#2378c3', family: 'Blue' },
  { token: 'blue-60', hex: '#2c608a', family: 'Blue' },
  { token: 'blue-70', hex: '#274863', family: 'Blue' },
  { token: 'blue-80', hex: '#1f303e', family: 'Blue' },
  { token: 'blue-90', hex: '#11181d', family: 'Blue' },
  { token: 'blue-5v', hex: '#e8f5ff', family: 'Blue' },
  { token: 'blue-10v', hex: '#cfe8ff', family: 'Blue' },
  { token: 'blue-20v', hex: '#a1d3ff', family: 'Blue' },
  { token: 'blue-30v', hex: '#58b4ff', family: 'Blue' },
  { token: 'blue-40v', hex: '#2491ff', family: 'Blue' },
  { token: 'blue-50v', hex: '#0076d6', family: 'Blue' },
  { token: 'blue-60v', hex: '#005ea2', family: 'Blue' },
  { token: 'blue-70v', hex: '#0b4778', family: 'Blue' },
  { token: 'blue-80v', hex: '#112f4e', family: 'Blue' },

  { token: 'blue-warm-5', hex: '#ecf1f7', family: 'Blue Warm' },
  { token: 'blue-warm-10', hex: '#e1e7f1', family: 'Blue Warm' },
  { token: 'blue-warm-20', hex: '#bbcae4', family: 'Blue Warm' },
  { token: 'blue-warm-30', hex: '#98afd2', family: 'Blue Warm' },
  { token: 'blue-warm-40', hex: '#7292c7', family: 'Blue Warm' },
  { token: 'blue-warm-50', hex: '#4a77b4', family: 'Blue Warm' },
  { token: 'blue-warm-60', hex: '#345d96', family: 'Blue Warm' },
  { token: 'blue-warm-70', hex: '#2f4668', family: 'Blue Warm' },
  { token: 'blue-warm-80', hex: '#252f3e', family: 'Blue Warm' },
  { token: 'blue-warm-90', hex: '#13171f', family: 'Blue Warm' },
  { token: 'blue-warm-5v', hex: '#edf5ff', family: 'Blue Warm' },
  { token: 'blue-warm-10v', hex: '#d4e5ff', family: 'Blue Warm' },
  { token: 'blue-warm-20v', hex: '#adcdff', family: 'Blue Warm' },
  { token: 'blue-warm-30v', hex: '#81aefc', family: 'Blue Warm' },
  { token: 'blue-warm-40v', hex: '#5994f6', family: 'Blue Warm' },
  { token: 'blue-warm-50v', hex: '#2672de', family: 'Blue Warm' },
  { token: 'blue-warm-60v', hex: '#0050d8', family: 'Blue Warm' },
  { token: 'blue-warm-70v', hex: '#1a4480', family: 'Blue Warm' },
  { token: 'blue-warm-80v', hex: '#162e51', family: 'Blue Warm' },

  { token: 'indigo-cool-5', hex: '#eef0f9', family: 'Indigo Cool' },
  { token: 'indigo-cool-10', hex: '#e1e6f9', family: 'Indigo Cool' },
  { token: 'indigo-cool-20', hex: '#bbc8f5', family: 'Indigo Cool' },
  { token: 'indigo-cool-30', hex: '#96abee', family: 'Indigo Cool' },
  { token: 'indigo-cool-40', hex: '#6b8ee8', family: 'Indigo Cool' },
  { token: 'indigo-cool-50', hex: '#496fd8', family: 'Indigo Cool' },
  { token: 'indigo-cool-60', hex: '#3f57a6', family: 'Indigo Cool' },
  { token: 'indigo-cool-70', hex: '#374274', family: 'Indigo Cool' },
  { token: 'indigo-cool-80', hex: '#292d42', family: 'Indigo Cool' },
  { token: 'indigo-cool-90', hex: '#151622', family: 'Indigo Cool' },
  { token: 'indigo-cool-5v', hex: '#edf0ff', family: 'Indigo Cool' },
  { token: 'indigo-cool-10v', hex: '#dee5ff', family: 'Indigo Cool' },
  { token: 'indigo-cool-20v', hex: '#b8c8ff', family: 'Indigo Cool' },
  { token: 'indigo-cool-30v', hex: '#94adff', family: 'Indigo Cool' },
  { token: 'indigo-cool-40v', hex: '#628ef4', family: 'Indigo Cool' },
  { token: 'indigo-cool-50v', hex: '#4866ff', family: 'Indigo Cool' },
  { token: 'indigo-cool-60v', hex: '#3e4ded', family: 'Indigo Cool' },
  { token: 'indigo-cool-70v', hex: '#222fbf', family: 'Indigo Cool' },
  { token: 'indigo-cool-80v', hex: '#1b2b85', family: 'Indigo Cool' },

  { token: 'indigo-5', hex: '#efeff8', family: 'Indigo' },
  { token: 'indigo-10', hex: '#e5e4fa', family: 'Indigo' },
  { token: 'indigo-20', hex: '#c5c5f3', family: 'Indigo' },
  { token: 'indigo-30', hex: '#a5a8eb', family: 'Indigo' },
  { token: 'indigo-40', hex: '#8889db', family: 'Indigo' },
  { token: 'indigo-50', hex: '#676cc8', family: 'Indigo' },
  { token: 'indigo-60', hex: '#4d52af', family: 'Indigo' },
  { token: 'indigo-70', hex: '#3d4076', family: 'Indigo' },
  { token: 'indigo-80', hex: '#2b2c40', family: 'Indigo' },
  { token: 'indigo-90', hex: '#16171f', family: 'Indigo' },
  { token: 'indigo-5v', hex: '#f0f0ff', family: 'Indigo' },
  { token: 'indigo-10v', hex: '#e0e0ff', family: 'Indigo' },
  { token: 'indigo-20v', hex: '#ccceff', family: 'Indigo' },
  { token: 'indigo-30v', hex: '#a3a7fa', family: 'Indigo' },
  { token: 'indigo-40v', hex: '#8289ff', family: 'Indigo' },
  { token: 'indigo-50v', hex: '#656bd7', family: 'Indigo' },
  { token: 'indigo-60v', hex: '#4a50c4', family: 'Indigo' },
  { token: 'indigo-70v', hex: '#3333a3', family: 'Indigo' },
  { token: 'indigo-80v', hex: '#212463', family: 'Indigo' },

  { token: 'indigo-warm-5', hex: '#f1eff7', family: 'Indigo Warm' },
  { token: 'indigo-warm-10', hex: '#e7e3fa', family: 'Indigo Warm' },
  { token: 'indigo-warm-20', hex: '#cbc4f2', family: 'Indigo Warm' },
  { token: 'indigo-warm-30', hex: '#afa5e8', family: 'Indigo Warm' },
  { token: 'indigo-warm-40', hex: '#9287d8', family: 'Indigo Warm' },
  { token: 'indigo-warm-50', hex: '#7665d1', family: 'Indigo Warm' },
  { token: 'indigo-warm-60', hex: '#5e519e', family: 'Indigo Warm' },
  { token: 'indigo-warm-70', hex: '#453c7b', family: 'Indigo Warm' },
  { token: 'indigo-warm-80', hex: '#2e2c40', family: 'Indigo Warm' },
  { token: 'indigo-warm-90', hex: '#18161d', family: 'Indigo Warm' },
  { token: 'indigo-warm-5v', hex: '#f5f2ff', family: 'Indigo Warm' },
  { token: 'indigo-warm-10v', hex: '#e4deff', family: 'Indigo Warm' },
  { token: 'indigo-warm-20v', hex: '#cfc4fd', family: 'Indigo Warm' },
  { token: 'indigo-warm-30v', hex: '#b69fff', family: 'Indigo Warm' },
  { token: 'indigo-warm-40v', hex: '#967efb', family: 'Indigo Warm' },
  { token: 'indigo-warm-50v', hex: '#745fe9', family: 'Indigo Warm' },
  { token: 'indigo-warm-60v', hex: '#5942d2', family: 'Indigo Warm' },
  { token: 'indigo-warm-70v', hex: '#3d2c9d', family: 'Indigo Warm' },
  { token: 'indigo-warm-80v', hex: '#261f5b', family: 'Indigo Warm' },

  { token: 'violet-5', hex: '#f4f1f9', family: 'Violet' },
  { token: 'violet-10', hex: '#ebe3f9', family: 'Violet' },
  { token: 'violet-20', hex: '#d0c3e9', family: 'Violet' },
  { token: 'violet-30', hex: '#b8a2e3', family: 'Violet' },
  { token: 'violet-40', hex: '#9d84d2', family: 'Violet' },
  { token: 'violet-50', hex: '#8168b3', family: 'Violet' },
  { token: 'violet-60', hex: '#665190', family: 'Violet' },
  { token: 'violet-70', hex: '#4c3d69', family: 'Violet' },
  { token: 'violet-80', hex: '#312b3f', family: 'Violet' },
  { token: 'violet-90', hex: '#18161d', family: 'Violet' },
  { token: 'violet-5v', hex: '#f7f2ff', family: 'Violet' },
  { token: 'violet-10v', hex: '#ede3ff', family: 'Violet' },
  { token: 'violet-20v', hex: '#d5bfff', family: 'Violet' },
  { token: 'violet-30v', hex: '#c39deb', family: 'Violet' },
  { token: 'violet-40v', hex: '#ad79e9', family: 'Violet' },
  { token: 'violet-50v', hex: '#9355dc', family: 'Violet' },
  { token: 'violet-60v', hex: '#783cb9', family: 'Violet' },
  { token: 'violet-70v', hex: '#54278f', family: 'Violet' },
  { token: 'violet-80v', hex: '#39215e', family: 'Violet' },

  { token: 'violet-warm-5', hex: '#f8f0f9', family: 'Violet Warm' },
  { token: 'violet-warm-10', hex: '#f6dff8', family: 'Violet Warm' },
  { token: 'violet-warm-20', hex: '#e2bee4', family: 'Violet Warm' },
  { token: 'violet-warm-30', hex: '#d29ad8', family: 'Violet Warm' },
  { token: 'violet-warm-40', hex: '#bf77c8', family: 'Violet Warm' },
  { token: 'violet-warm-50', hex: '#b04abd', family: 'Violet Warm' },
  { token: 'violet-warm-60', hex: '#864381', family: 'Violet Warm' },
  { token: 'violet-warm-70', hex: '#5c395a', family: 'Violet Warm' },
  { token: 'violet-warm-80', hex: '#382936', family: 'Violet Warm' },
  { token: 'violet-warm-90', hex: '#1b151b', family: 'Violet Warm' },
  { token: 'violet-warm-5v', hex: '#fef2ff', family: 'Violet Warm' },
  { token: 'violet-warm-10v', hex: '#fbdcff', family: 'Violet Warm' },
  { token: 'violet-warm-20v', hex: '#f4b2ff', family: 'Violet Warm' },
  { token: 'violet-warm-30v', hex: '#ee83ff', family: 'Violet Warm' },
  { token: 'violet-warm-40v', hex: '#d85bef', family: 'Violet Warm' },
  { token: 'violet-warm-50v', hex: '#be32d0', family: 'Violet Warm' },
  { token: 'violet-warm-60v', hex: '#93348c', family: 'Violet Warm' },
  { token: 'violet-warm-70v', hex: '#711e6c', family: 'Violet Warm' },
  { token: 'violet-warm-80v', hex: '#481441', family: 'Violet Warm' },

  { token: 'magenta-5', hex: '#f9f0f2', family: 'Magenta' },
  { token: 'magenta-10', hex: '#f6e1e8', family: 'Magenta' },
  { token: 'magenta-20', hex: '#f0bbcc', family: 'Magenta' },
  { token: 'magenta-30', hex: '#e895b3', family: 'Magenta' },
  { token: 'magenta-40', hex: '#e0699f', family: 'Magenta' },
  { token: 'magenta-50', hex: '#c84281', family: 'Magenta' },
  { token: 'magenta-60', hex: '#8b4566', family: 'Magenta' },
  { token: 'magenta-70', hex: '#66364b', family: 'Magenta' },
  { token: 'magenta-80', hex: '#402731', family: 'Magenta' },
  { token: 'magenta-90', hex: '#1b1617', family: 'Magenta' },
  { token: 'magenta-5v', hex: '#fff2f5', family: 'Magenta' },
  { token: 'magenta-10v', hex: '#ffddea', family: 'Magenta' },
  { token: 'magenta-20v', hex: '#ffb4cf', family: 'Magenta' },
  { token: 'magenta-30v', hex: '#ff87b2', family: 'Magenta' },
  { token: 'magenta-40v', hex: '#fd4496', family: 'Magenta' },
  { token: 'magenta-50v', hex: '#d72d79', family: 'Magenta' },
  { token: 'magenta-60v', hex: '#ab2165', family: 'Magenta' },
  { token: 'magenta-70v', hex: '#731f44', family: 'Magenta' },
  { token: 'magenta-80v', hex: '#4f172e', family: 'Magenta' },

  { token: 'gray-cool-1', hex: '#fbfcfd', family: 'Gray Cool' },
  { token: 'gray-cool-2', hex: '#f7f9fa', family: 'Gray Cool' },
  { token: 'gray-cool-3', hex: '#f5f6f7', family: 'Gray Cool' },
  { token: 'gray-cool-4', hex: '#f1f3f6', family: 'Gray Cool' },
  { token: 'gray-cool-5', hex: '#edeff0', family: 'Gray Cool' },
  { token: 'gray-cool-10', hex: '#dfe1e2', family: 'Gray Cool' },
  { token: 'gray-cool-20', hex: '#c6cace', family: 'Gray Cool' },
  { token: 'gray-cool-30', hex: '#a9aeb1', family: 'Gray Cool' },
  { token: 'gray-cool-40', hex: '#8d9297', family: 'Gray Cool' },
  { token: 'gray-cool-50', hex: '#71767a', family: 'Gray Cool' },
  { token: 'gray-cool-60', hex: '#565c65', family: 'Gray Cool' },
  { token: 'gray-cool-70', hex: '#3d4551', family: 'Gray Cool' },
  { token: 'gray-cool-80', hex: '#2d2e2f', family: 'Gray Cool' },
  { token: 'gray-cool-90', hex: '#1c1d1f', family: 'Gray Cool' },

  { token: 'gray-1', hex: '#fcfcfc', family: 'Gray' },
  { token: 'gray-2', hex: '#f9f9f9', family: 'Gray' },
  { token: 'gray-3', hex: '#f6f6f6', family: 'Gray' },
  { token: 'gray-4', hex: '#f3f3f3', family: 'Gray' },
  { token: 'gray-5', hex: '#f0f0f0', family: 'Gray' },
  { token: 'gray-10', hex: '#e6e6e6', family: 'Gray' },
  { token: 'gray-20', hex: '#c9c9c9', family: 'Gray' },
  { token: 'gray-30', hex: '#adadad', family: 'Gray' },
  { token: 'gray-40', hex: '#919191', family: 'Gray' },
  { token: 'gray-50', hex: '#757575', family: 'Gray' },
  { token: 'gray-60', hex: '#5c5c5c', family: 'Gray' },
  { token: 'gray-70', hex: '#454545', family: 'Gray' },
  { token: 'gray-80', hex: '#2e2e2e', family: 'Gray' },
  { token: 'gray-90', hex: '#1b1b1b', family: 'Gray' },

  { token: 'gray-warm-1', hex: '#fcfcfb', family: 'Gray Warm' },
  { token: 'gray-warm-2', hex: '#f9f9f7', family: 'Gray Warm' },
  { token: 'gray-warm-3', hex: '#f6f6f2', family: 'Gray Warm' },
  { token: 'gray-warm-4', hex: '#f5f5f0', family: 'Gray Warm' },
  { token: 'gray-warm-5', hex: '#f0f0ec', family: 'Gray Warm' },
  { token: 'gray-warm-10', hex: '#e6e6e2', family: 'Gray Warm' },
  { token: 'gray-warm-20', hex: '#cac9c0', family: 'Gray Warm' },
  { token: 'gray-warm-30', hex: '#afaea2', family: 'Gray Warm' },
  { token: 'gray-warm-40', hex: '#929285', family: 'Gray Warm' },
  { token: 'gray-warm-50', hex: '#76766a', family: 'Gray Warm' },
  { token: 'gray-warm-60', hex: '#5d5d52', family: 'Gray Warm' },
  { token: 'gray-warm-70', hex: '#454540', family: 'Gray Warm' },
  { token: 'gray-warm-80', hex: '#2e2e2a', family: 'Gray Warm' },
  { token: 'gray-warm-90', hex: '#171716', family: 'Gray Warm' },
]

export const findTokenByHex = (hex: string | undefined | null): UswdsColorToken | undefined => {
  if (!hex) return undefined
  const normalized = hex.toLowerCase()
  return uswdsColorTokens.find((c) => c.hex.toLowerCase() === normalized)
}
