import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "site_config_site_collection" ADD COLUMN "theme_color_primary" varchar DEFAULT '#112f4e';
  ALTER TABLE "site_config_site_collection" ADD COLUMN "theme_color_primary_on" varchar DEFAULT '#ffffff';
  ALTER TABLE "site_config_site_collection" ADD COLUMN "theme_color_secondary" varchar DEFAULT '#005ea2';
  ALTER TABLE "site_config_site_collection" ADD COLUMN "theme_color_secondary_on" varchar DEFAULT '#ffffff';
  ALTER TABLE "site_config_site_collection" ADD COLUMN "theme_color_accent" varchar DEFAULT '#8b0a03';
  ALTER TABLE "site_config_site_collection" ADD COLUMN "theme_color_text" varchar DEFAULT '#1b1b1b';
  ALTER TABLE "site_config_site_collection" ADD COLUMN "theme_color_bg" varchar DEFAULT '#ffffff';
  ALTER TABLE "site_config_site_collection" ADD COLUMN "theme_color_surface" varchar DEFAULT '#fcfcfc';
  ALTER TABLE "site_config_site_collection" ADD COLUMN "theme_color_border" varchar DEFAULT '#e6e6e6';
  ALTER TABLE "site_config_site_collection" ADD COLUMN "theme_color_link" varchar DEFAULT '#112f4e';
  ALTER TABLE "site_config_site_collection" ADD COLUMN "theme_font_body" varchar DEFAULT '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';
  ALTER TABLE "site_config_site_collection" ADD COLUMN "theme_font_heading" varchar DEFAULT '"Playfair Display", Georgia, "Times New Roman", Times, serif';
  ALTER TABLE "site_config_site_collection" ADD COLUMN "theme_layout_max_width" varchar DEFAULT '75rem';
  ALTER TABLE "site_config_site_collection" ADD COLUMN "theme_space_section_y" varchar DEFAULT '2rem';
  ALTER TABLE "site_config_site_collection" ADD COLUMN "theme_radius_md" varchar DEFAULT '0.25rem';
  ALTER TABLE "site_config_site_collection" ADD COLUMN "theme_custom_css" varchar DEFAULT '';
  ALTER TABLE "_site_config_site_collection_v" ADD COLUMN "version_theme_color_primary" varchar DEFAULT '#112f4e';
  ALTER TABLE "_site_config_site_collection_v" ADD COLUMN "version_theme_color_primary_on" varchar DEFAULT '#ffffff';
  ALTER TABLE "_site_config_site_collection_v" ADD COLUMN "version_theme_color_secondary" varchar DEFAULT '#005ea2';
  ALTER TABLE "_site_config_site_collection_v" ADD COLUMN "version_theme_color_secondary_on" varchar DEFAULT '#ffffff';
  ALTER TABLE "_site_config_site_collection_v" ADD COLUMN "version_theme_color_accent" varchar DEFAULT '#8b0a03';
  ALTER TABLE "_site_config_site_collection_v" ADD COLUMN "version_theme_color_text" varchar DEFAULT '#1b1b1b';
  ALTER TABLE "_site_config_site_collection_v" ADD COLUMN "version_theme_color_bg" varchar DEFAULT '#ffffff';
  ALTER TABLE "_site_config_site_collection_v" ADD COLUMN "version_theme_color_surface" varchar DEFAULT '#fcfcfc';
  ALTER TABLE "_site_config_site_collection_v" ADD COLUMN "version_theme_color_border" varchar DEFAULT '#e6e6e6';
  ALTER TABLE "_site_config_site_collection_v" ADD COLUMN "version_theme_color_link" varchar DEFAULT '#112f4e';
  ALTER TABLE "_site_config_site_collection_v" ADD COLUMN "version_theme_font_body" varchar DEFAULT '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';
  ALTER TABLE "_site_config_site_collection_v" ADD COLUMN "version_theme_font_heading" varchar DEFAULT '"Playfair Display", Georgia, "Times New Roman", Times, serif';
  ALTER TABLE "_site_config_site_collection_v" ADD COLUMN "version_theme_layout_max_width" varchar DEFAULT '75rem';
  ALTER TABLE "_site_config_site_collection_v" ADD COLUMN "version_theme_space_section_y" varchar DEFAULT '2rem';
  ALTER TABLE "_site_config_site_collection_v" ADD COLUMN "version_theme_radius_md" varchar DEFAULT '0.25rem';
  ALTER TABLE "_site_config_site_collection_v" ADD COLUMN "version_theme_custom_css" varchar DEFAULT '';
  ALTER TABLE "site_config" ADD COLUMN "theme_color_primary" varchar DEFAULT '#112f4e';
  ALTER TABLE "site_config" ADD COLUMN "theme_color_primary_on" varchar DEFAULT '#ffffff';
  ALTER TABLE "site_config" ADD COLUMN "theme_color_secondary" varchar DEFAULT '#005ea2';
  ALTER TABLE "site_config" ADD COLUMN "theme_color_secondary_on" varchar DEFAULT '#ffffff';
  ALTER TABLE "site_config" ADD COLUMN "theme_color_accent" varchar DEFAULT '#8b0a03';
  ALTER TABLE "site_config" ADD COLUMN "theme_color_text" varchar DEFAULT '#1b1b1b';
  ALTER TABLE "site_config" ADD COLUMN "theme_color_bg" varchar DEFAULT '#ffffff';
  ALTER TABLE "site_config" ADD COLUMN "theme_color_surface" varchar DEFAULT '#fcfcfc';
  ALTER TABLE "site_config" ADD COLUMN "theme_color_border" varchar DEFAULT '#e6e6e6';
  ALTER TABLE "site_config" ADD COLUMN "theme_color_link" varchar DEFAULT '#112f4e';
  ALTER TABLE "site_config" ADD COLUMN "theme_font_body" varchar DEFAULT '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';
  ALTER TABLE "site_config" ADD COLUMN "theme_font_heading" varchar DEFAULT '"Playfair Display", Georgia, "Times New Roman", Times, serif';
  ALTER TABLE "site_config" ADD COLUMN "theme_layout_max_width" varchar DEFAULT '75rem';
  ALTER TABLE "site_config" ADD COLUMN "theme_space_section_y" varchar DEFAULT '2rem';
  ALTER TABLE "site_config" ADD COLUMN "theme_radius_md" varchar DEFAULT '0.25rem';
  ALTER TABLE "site_config" ADD COLUMN "theme_custom_css" varchar DEFAULT '';
  ALTER TABLE "_site_config_v" ADD COLUMN "version_theme_color_primary" varchar DEFAULT '#112f4e';
  ALTER TABLE "_site_config_v" ADD COLUMN "version_theme_color_primary_on" varchar DEFAULT '#ffffff';
  ALTER TABLE "_site_config_v" ADD COLUMN "version_theme_color_secondary" varchar DEFAULT '#005ea2';
  ALTER TABLE "_site_config_v" ADD COLUMN "version_theme_color_secondary_on" varchar DEFAULT '#ffffff';
  ALTER TABLE "_site_config_v" ADD COLUMN "version_theme_color_accent" varchar DEFAULT '#8b0a03';
  ALTER TABLE "_site_config_v" ADD COLUMN "version_theme_color_text" varchar DEFAULT '#1b1b1b';
  ALTER TABLE "_site_config_v" ADD COLUMN "version_theme_color_bg" varchar DEFAULT '#ffffff';
  ALTER TABLE "_site_config_v" ADD COLUMN "version_theme_color_surface" varchar DEFAULT '#fcfcfc';
  ALTER TABLE "_site_config_v" ADD COLUMN "version_theme_color_border" varchar DEFAULT '#e6e6e6';
  ALTER TABLE "_site_config_v" ADD COLUMN "version_theme_color_link" varchar DEFAULT '#112f4e';
  ALTER TABLE "_site_config_v" ADD COLUMN "version_theme_font_body" varchar DEFAULT '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';
  ALTER TABLE "_site_config_v" ADD COLUMN "version_theme_font_heading" varchar DEFAULT '"Playfair Display", Georgia, "Times New Roman", Times, serif';
  ALTER TABLE "_site_config_v" ADD COLUMN "version_theme_layout_max_width" varchar DEFAULT '75rem';
  ALTER TABLE "_site_config_v" ADD COLUMN "version_theme_space_section_y" varchar DEFAULT '2rem';
  ALTER TABLE "_site_config_v" ADD COLUMN "version_theme_radius_md" varchar DEFAULT '0.25rem';
  ALTER TABLE "_site_config_v" ADD COLUMN "version_theme_custom_css" varchar DEFAULT '';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "site_config_site_collection" DROP COLUMN "theme_color_primary";
  ALTER TABLE "site_config_site_collection" DROP COLUMN "theme_color_primary_on";
  ALTER TABLE "site_config_site_collection" DROP COLUMN "theme_color_secondary";
  ALTER TABLE "site_config_site_collection" DROP COLUMN "theme_color_secondary_on";
  ALTER TABLE "site_config_site_collection" DROP COLUMN "theme_color_accent";
  ALTER TABLE "site_config_site_collection" DROP COLUMN "theme_color_text";
  ALTER TABLE "site_config_site_collection" DROP COLUMN "theme_color_bg";
  ALTER TABLE "site_config_site_collection" DROP COLUMN "theme_color_surface";
  ALTER TABLE "site_config_site_collection" DROP COLUMN "theme_color_border";
  ALTER TABLE "site_config_site_collection" DROP COLUMN "theme_color_link";
  ALTER TABLE "site_config_site_collection" DROP COLUMN "theme_font_body";
  ALTER TABLE "site_config_site_collection" DROP COLUMN "theme_font_heading";
  ALTER TABLE "site_config_site_collection" DROP COLUMN "theme_layout_max_width";
  ALTER TABLE "site_config_site_collection" DROP COLUMN "theme_space_section_y";
  ALTER TABLE "site_config_site_collection" DROP COLUMN "theme_radius_md";
  ALTER TABLE "site_config_site_collection" DROP COLUMN "theme_custom_css";
  ALTER TABLE "_site_config_site_collection_v" DROP COLUMN "version_theme_color_primary";
  ALTER TABLE "_site_config_site_collection_v" DROP COLUMN "version_theme_color_primary_on";
  ALTER TABLE "_site_config_site_collection_v" DROP COLUMN "version_theme_color_secondary";
  ALTER TABLE "_site_config_site_collection_v" DROP COLUMN "version_theme_color_secondary_on";
  ALTER TABLE "_site_config_site_collection_v" DROP COLUMN "version_theme_color_accent";
  ALTER TABLE "_site_config_site_collection_v" DROP COLUMN "version_theme_color_text";
  ALTER TABLE "_site_config_site_collection_v" DROP COLUMN "version_theme_color_bg";
  ALTER TABLE "_site_config_site_collection_v" DROP COLUMN "version_theme_color_surface";
  ALTER TABLE "_site_config_site_collection_v" DROP COLUMN "version_theme_color_border";
  ALTER TABLE "_site_config_site_collection_v" DROP COLUMN "version_theme_color_link";
  ALTER TABLE "_site_config_site_collection_v" DROP COLUMN "version_theme_font_body";
  ALTER TABLE "_site_config_site_collection_v" DROP COLUMN "version_theme_font_heading";
  ALTER TABLE "_site_config_site_collection_v" DROP COLUMN "version_theme_layout_max_width";
  ALTER TABLE "_site_config_site_collection_v" DROP COLUMN "version_theme_space_section_y";
  ALTER TABLE "_site_config_site_collection_v" DROP COLUMN "version_theme_radius_md";
  ALTER TABLE "_site_config_site_collection_v" DROP COLUMN "version_theme_custom_css";
  ALTER TABLE "site_config" DROP COLUMN "theme_color_primary";
  ALTER TABLE "site_config" DROP COLUMN "theme_color_primary_on";
  ALTER TABLE "site_config" DROP COLUMN "theme_color_secondary";
  ALTER TABLE "site_config" DROP COLUMN "theme_color_secondary_on";
  ALTER TABLE "site_config" DROP COLUMN "theme_color_accent";
  ALTER TABLE "site_config" DROP COLUMN "theme_color_text";
  ALTER TABLE "site_config" DROP COLUMN "theme_color_bg";
  ALTER TABLE "site_config" DROP COLUMN "theme_color_surface";
  ALTER TABLE "site_config" DROP COLUMN "theme_color_border";
  ALTER TABLE "site_config" DROP COLUMN "theme_color_link";
  ALTER TABLE "site_config" DROP COLUMN "theme_font_body";
  ALTER TABLE "site_config" DROP COLUMN "theme_font_heading";
  ALTER TABLE "site_config" DROP COLUMN "theme_layout_max_width";
  ALTER TABLE "site_config" DROP COLUMN "theme_space_section_y";
  ALTER TABLE "site_config" DROP COLUMN "theme_radius_md";
  ALTER TABLE "site_config" DROP COLUMN "theme_custom_css";
  ALTER TABLE "_site_config_v" DROP COLUMN "version_theme_color_primary";
  ALTER TABLE "_site_config_v" DROP COLUMN "version_theme_color_primary_on";
  ALTER TABLE "_site_config_v" DROP COLUMN "version_theme_color_secondary";
  ALTER TABLE "_site_config_v" DROP COLUMN "version_theme_color_secondary_on";
  ALTER TABLE "_site_config_v" DROP COLUMN "version_theme_color_accent";
  ALTER TABLE "_site_config_v" DROP COLUMN "version_theme_color_text";
  ALTER TABLE "_site_config_v" DROP COLUMN "version_theme_color_bg";
  ALTER TABLE "_site_config_v" DROP COLUMN "version_theme_color_surface";
  ALTER TABLE "_site_config_v" DROP COLUMN "version_theme_color_border";
  ALTER TABLE "_site_config_v" DROP COLUMN "version_theme_color_link";
  ALTER TABLE "_site_config_v" DROP COLUMN "version_theme_font_body";
  ALTER TABLE "_site_config_v" DROP COLUMN "version_theme_font_heading";
  ALTER TABLE "_site_config_v" DROP COLUMN "version_theme_layout_max_width";
  ALTER TABLE "_site_config_v" DROP COLUMN "version_theme_space_section_y";
  ALTER TABLE "_site_config_v" DROP COLUMN "version_theme_radius_md";
  ALTER TABLE "_site_config_v" DROP COLUMN "version_theme_custom_css";`)
}
