/**
 * Script to export globals (home page, menu, side navigation) to seed data files
 * 
 * Usage:
 *   npm run export:globals [siteId]
 * 
 * If siteId is provided, exports that site's globals.
 * If not provided, exports the first site found.
 * 
 * This will fetch the current globals from the database and
 * update the seed data files in scripts/datasets/
 */

import { getPayload } from 'payload'
import config from '@payload-config'
import * as fs from 'fs'
import * as path from 'path'

const payload = await getPayload({ config })

// Get site ID from command line argument or find first site
let siteId: number | undefined
const args = process.argv.slice(2)
if (args[0]) {
  siteId = parseInt(args[0], 10)
  if (isNaN(siteId)) {
    console.error(`Invalid site ID: ${args[0]}`)
    process.exit(1)
  }
} else {
  // Find first site
  const sites = await payload.find({
    collection: 'sites',
    limit: 1,
  })
  if (sites.docs.length === 0) {
    console.error('No sites found in database')
    process.exit(1)
  }
  siteId = sites.docs[0].id
  console.log(`No site ID provided, using first site: ${sites.docs[0].name} (ID: ${siteId})`)
}

function cleanGlobalData(data: any) {
  // Remove internal fields that shouldn't be in seed data
  const { id, updatedAt, createdAt, _status, site, ...cleaned } = data
  return cleaned
}

function escapeUnsafeChars(str: string): string {
  const charMap: { [key: string]: string } = {
    '<': '\\u003C',
    '>': '\\u003E',
    '/': '\\u002F',
    '\\': '\\\\',
    '\b': '\\b',
    '\f': '\\f',
    '\n': '\\n',
    '\r': '\\r',
    '\t': '\\t',
    '\0': '\\0',
    '\u2028': '\\u2028',
    '\u2029': '\\u2029',
  }
  // Match all relevant unsafe characters
  return str.replace(/[<>\b\f\n\r\t\0\u2028\u2029/\\]/g, x => charMap[x] || x)
}

function formatSeedFile(name: string, data: any, description: string) {
  const safeJson = escapeUnsafeChars(JSON.stringify(data, null, 2))
  return `// ${description}
// This file was generated by the export-globals script
// Last exported: ${new Date().toISOString()}
// 
// To update this file manually, edit the content object below.
// To regenerate from the database, run: npm run export:globals

const ${name} = () => (${safeJson})

export default ${name}
`
}

async function exportHomePage() {
  try {
    // Query the site collection directly since it's a site-specific global
    const homePageDocs = await payload.find({
      collection: 'home-page-site-collection',
      where: {
        site: { equals: siteId },
      },
      depth: 2,
    })

    if (homePageDocs.docs.length === 0) {
      console.log('⚠️  No home page found for this site.')
      return
    }

    const homePage = homePageDocs.docs[0]
    const seedData = cleanGlobalData(homePage)
    const fileContent = formatSeedFile('homePage', seedData, 'Home page seed data')
    const filePath = path.join(process.cwd(), 'scripts', 'datasets', 'homePage.ts')
    fs.writeFileSync(filePath, fileContent, 'utf-8')
    console.log('✅ Home page data exported successfully!')
  } catch (error) {
    console.error('❌ Error exporting home page:', error)
  }
}

async function exportMenu() {
  try {
    // Query the site collection directly since it's a site-specific global
    const menuDocs = await payload.find({
      collection: 'menu-site-collection',
      where: {
        site: { equals: siteId },
      },
      depth: 2,
    })

    if (menuDocs.docs.length === 0) {
      console.log('⚠️  No menu found for this site.')
      return
    }

    const menu = menuDocs.docs[0]
    const seedData = cleanGlobalData(menu)
    const fileContent = formatSeedFile('menu', seedData, 'Main navigation menu seed data')
    const filePath = path.join(process.cwd(), 'scripts', 'datasets', 'menu.ts')
    fs.writeFileSync(filePath, fileContent, 'utf-8')
    console.log('✅ Menu data exported successfully!')
  } catch (error) {
    console.error('❌ Error exporting menu:', error)
  }
}

async function exportSideNavigation() {
  try {
    // Query the site collection directly since it's a site-specific global
    const sideNavDocs = await payload.find({
      collection: 'side-navigation-site-collection',
      where: {
        site: { equals: siteId },
      },
      depth: 2,
    })

    if (sideNavDocs.docs.length === 0) {
      console.log('⚠️  No side navigation found for this site.')
      return
    }

    const sideNavigation = sideNavDocs.docs[0]
    const seedData = cleanGlobalData(sideNavigation)
    const fileContent = formatSeedFile(
      'sideNavigation',
      seedData,
      'Side navigation menu seed data',
    )
    const filePath = path.join(process.cwd(), 'scripts', 'datasets', 'sideNavigation.ts')
    fs.writeFileSync(filePath, fileContent, 'utf-8')
    console.log('✅ Side navigation data exported successfully!')
  } catch (error) {
    console.error('❌ Error exporting side navigation:', error)
  }
}

async function exportGlobals() {
  console.log(`📦 Exporting globals for site ID: ${siteId}...\n`)
  await exportHomePage()
  await exportMenu()
  await exportSideNavigation()
  console.log('\n💡 To use this data in seeding, run: npm run dc:seed')
}

await exportGlobals()
process.exit(0)

